<?php

/**
 * This is the model base class for the table "message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Message".
 *
 * Columns in table "message" available as properties of the model,
 * followed by relations of table "message" available as properties of the model.
 *
 * @property integer $id
 * @property string $user_from_id
 * @property string $user_to_id
 * @property string $idea_to_id
 * @property string $time_sent
 * @property string $message
 *
 * @property Idea $ideaTo
 * @property User $userFrom
 * @property User $userTo
 */
abstract class BaseMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Message|Messages', $n);
	}

	public static function representingColumn() {
		return 'time_sent';
	}

	public function rules() {
		return array(
      array('time_sent', 'default', 'value' => date('Y-m-d H:i:s'), 'setOnEmpty' => true, 'on' => 'insert'),
			array('user_from_id,  message', 'required'),
			array('user_from_id, user_to_id, idea_to_id', 'length', 'max'=>11),
			array('user_to_id, idea_to_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_from_id, user_to_id, idea_to_id, time_sent, message', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ideaTo' => array(self::BELONGS_TO, 'Idea', 'idea_to_id'),
			'userFrom' => array(self::BELONGS_TO, 'User', 'user_from_id'),
			'userTo' => array(self::BELONGS_TO, 'User', 'user_to_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_from_id' => null,
			'user_to_id' => null,
			'idea_to_id' => null,
			'time_sent' => Yii::t('app', 'Time Sent'),
			'message' => Yii::t('app', 'Message'),
			'ideaTo' => null,
			'userFrom' => null,
			'userTo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_from_id', $this->user_from_id);
		$criteria->compare('user_to_id', $this->user_to_id);
		$criteria->compare('idea_to_id', $this->idea_to_id);
		$criteria->compare('time_sent', $this->time_sent, true);
		$criteria->compare('message', $this->message, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}