<?php

/**
 * This is the model base class for the table "action_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActionLog".
 *
 * Columns in table "action_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $user_id
 * @property string $ipaddress
 * @property string $logtime
 * @property string $controller
 * @property string $action
 * @property string $details
 *
 */
abstract class BaseActionLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'action_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ActionLog|ActionLogs', $n);
	}

	public static function representingColumn() {
		return 'ipaddress';
	}

	public function rules() {
		return array(
			array('ipaddress, logtime', 'required'),
			array('user_id', 'length', 'max'=>10),
			array('ipaddress', 'length', 'max'=>50),
			array('controller, action', 'length', 'max'=>255),
			array('details', 'safe'),
			array('user_id, controller, action, details', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, ipaddress, logtime, controller, action, details', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'ipaddress' => Yii::t('app', 'Ipaddress'),
			'logtime' => Yii::t('app', 'Logtime'),
			'controller' => Yii::t('app', 'Controller'),
			'action' => Yii::t('app', 'Action'),
			'details' => Yii::t('app', 'Details'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('ipaddress', $this->ipaddress, true);
		$criteria->compare('logtime', $this->logtime, true);
		$criteria->compare('controller', $this->controller, true);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('details', $this->details, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}