<?php

/**
 * This is the model base class for the table "message".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Message".
 *
 * Columns in table "message" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_from_id
 * @property integer $user_to_id
 * @property integer $idea_to_id
 * @property string $time_sent
 * @property string $message
 *
 */
abstract class BaseMessage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'message';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Message|Messages', $n);
	}

	public static function representingColumn() {
		return 'time_sent';
	}

	public function rules() {
		return array(
			array('user_from_id, time_sent, message', 'required'),
			array('user_from_id, user_to_id, idea_to_id', 'numerical', 'integerOnly'=>true),
			array('user_to_id, idea_to_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_from_id, user_to_id, idea_to_id, time_sent, message', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_from_id' => Yii::t('app', 'User From'),
			'user_to_id' => Yii::t('app', 'User To'),
			'idea_to_id' => Yii::t('app', 'Idea To'),
			'time_sent' => Yii::t('app', 'Time Sent'),
			'message' => Yii::t('app', 'Message'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_from_id', $this->user_from_id);
		$criteria->compare('user_to_id', $this->user_to_id);
		$criteria->compare('idea_to_id', $this->idea_to_id);
		$criteria->compare('time_sent', $this->time_sent, true);
		$criteria->compare('message', $this->message, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}