<?php

/**
 * This is the model base class for the table "mail_click_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MailClickLog".
 *
 * Columns in table "mail_click_log" available as properties of the model,
 * followed by relations of table "mail_click_log" available as properties of the model.
 *
 * @property integer $id
 * @property string $mail_id
 * @property string $link
 * @property string $time_clicked
 * @property string $button_name
 *
 * @property MailLog $mail
 */
abstract class BaseMailClickLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mail_click_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MailClickLog|MailClickLogs', $n);
	}

	public static function representingColumn() {
		return 'link';
	}

	public function rules() {
		return array(
			array('mail_id, link, time_clicked, button_name', 'required'),
			array('mail_id', 'length', 'max'=>10),
			array('link', 'length', 'max'=>255),
			array('button_name', 'length', 'max'=>200),
			array('id, mail_id, link, time_clicked, button_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mail' => array(self::BELONGS_TO, 'MailLog', 'mail_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'mail_id' => null,
			'link' => Yii::t('app', 'Link'),
			'time_clicked' => Yii::t('app', 'Time Clicked'),
			'button_name' => Yii::t('app', 'Button Name'),
			'mail' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('mail_id', $this->mail_id);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('time_clicked', $this->time_clicked, true);
		$criteria->compare('button_name', $this->button_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}