<?php

/**
 * This is the model base class for the table "links".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Links".
 *
 * Columns in table "links" available as properties of the model,
 * followed by relations of table "links" available as properties of the model.
 *
 * @property string $ID
 * @property string $name
 * @property string $url
 *
 * @property UsersLinks[] $usersLinks
 */
abstract class BaseLinks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'links';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Links|Links', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, url', 'required'),
			array('name, url', 'length', 'max'=>128),
			array('ID, name, url', 'safe', 'on'=>'search'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}