<?php

/**
 * This is the model base class for the table "languages".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Languages".
 *
 * Columns in table "languages" available as properties of the model,
 * followed by relations of table "languages" available as properties of the model.
 *
 * @property integer $ID
 * @property string $language_code
 * @property string $name
 *
 * @property IdeasTranslations[] $ideasTranslations
 * @property Translations[] $translations
 * @property Users[] $users
 */
abstract class BaseLanguages extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'languages';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Languages|Languages', $n);
	}

	public static function representingColumn() {
		return 'language_code';
	}

	public function rules() {
		return array(
			array('language_code, name', 'required'),
			array('language_code', 'length', 'max'=>2),
			array('name', 'length', 'max'=>32),
			array('ID, language_code, name', 'safe', 'on'=>'search'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'language_code' => Yii::t('app', 'Language Code'),
			'name' => Yii::t('app', 'Name'),
			'ideasTranslations' => null,
			'translations' => null,
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID);
		$criteria->compare('language_code', $this->language_code, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}