<?php

/**
 * This is the model base class for the table "user_stat".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserStat".
 *
 * Columns in table "user_stat" available as properties of the model,
 * followed by relations of table "user_stat" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property integer $completeness
 * @property integer $invites_send
 * @property integer $invites_registered
 * @property integer $reputation
 *
 * @property User $user
 */
abstract class BaseUserStat extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_stat';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserStat|UserStats', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('completeness, invites_send, invites_registered, reputation', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>10),
			array('completeness, invites_send, invites_registered, reputation', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, completeness, invites_send, invites_registered, reputation', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'completeness' => Yii::t('app', 'completeness'),
			'invites_send' => Yii::t('app', 'Invitations Send'),
			'invites_registered' => Yii::t('app', 'Invites Registered'),
			'reputation' => Yii::t('app', 'Reputation'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('completeness', $this->completeness);
		$criteria->compare('invites_send', $this->invites_send);
		$criteria->compare('invites_registered', $this->invites_registered);
		$criteria->compare('reputation', $this->reputation);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}