<?php

/**
 * This is the model base class for the table "click_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ClickUser".
 *
 * Columns in table "click_user" available as properties of the model,
 * followed by relations of table "click_user" available as properties of the model.
 *
 * @property string $id
 * @property string $time
 *
 * @property User $userClick
 * @property User $user
 */
abstract class BaseClickUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'click_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ClickUser|ClickUsers', $n);
	}

	public static function representingColumn() {
		return 'time';
	}

	public function rules() {
		return array(
			array('time', 'required'),
			array('id, time', 'safe', 'on'=>'search'),
		);
	}

/*	public function relations() {
		return array(
			'userClick' => array(self::BELONGS_TO, 'User', 'user_click_id'),
			'user' => array(self::BELONGS_TO, 'User'),
		);
	}*/

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'time' => Yii::t('app', 'Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('time', $this->time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}