<?php

/**
 * This is the model base class for the table "ideas_statuses".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IdeasStatuses".
 *
 * Columns in table "ideas_statuses" available as properties of the model,
 * followed by relations of table "ideas_statuses" available as properties of the model.
 *
 * @property integer $ID
 * @property integer $name
 *
 * @property Ideas[] $ideases
 */
abstract class BaseIdeasStatuses extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ideas_statuses';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IdeasStatuses|IdeasStatuses', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'numerical', 'integerOnly'=>true),
			array('ID, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ideases' => array(self::HAS_MANY, 'Ideas', 'status_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'ideases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID);
		$criteria->compare('name', $this->name);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}