<?php

/**
 * This is the model base class for the table "skillset".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Skillset".
 *
 * Columns in table "skillset" available as properties of the model,
 * followed by relations of table "skillset" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property SkillsetSkill[] $skillsetSkills
 * @property UserSkill[] $userSkills
 */
abstract class BaseIndustry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'industry';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Industry|Industries', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>128),
			array('count' 'numerical', 'integerOnly'=>true),
			array('count', 'length', 'max'=>11),
			array('count', 'default', 'setOnEmpty' => true, 'value' => 1),
			array('id, name, count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'industries' => array(self::HAS_MANY, 'Industry', 'industry_id'),
			'userIndustries' => array(self::HAS_MANY, 'UserIndustry', 'industry_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'count' => null,
			'industries' => null,
			'userIndustries' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('count', $this->count, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}