<?php

/**
 * This is the model base class for the table "skill".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Skill".
 *
 * Columns in table "skill" available as properties of the model,
 * followed by relations of table "skill" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 */
abstract class BaseSkill extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'skill';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Skill|Skills', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'unique'),
			array('name', 'length', 'max'=>128),
			array('count', 'length', 'max'=>11),
			array('count', 'default', 'setOnEmpty' => true, 'value' => 1),
			array('id, name, count', 'safe', 'on'=>'search'),
		);
	}

	/*public function relations() {
		return array(
			'skillsetSkills' => array(self::HAS_MANY, 'SkillsetSkill', 'skill_id'),
			'userSkills' => array(self::HAS_MANY, 'UserSkill', 'skill_id'),
		);
	}*/

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'count' => NULL,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('count', $this->count, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}