<?php

/**
 * This is the model base class for the table "City".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "City".
 *
 * Columns in table "City" available as properties of the model,
 * followed by relations of table "City" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 *
 * @property UserShare[] $userShares
 * @property UserTmp[] $userTmps
 */
abstract class BaseCity extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'City';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'City|Cities', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>64),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}