<?php

/**
 * This is the model base class for the table "link".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Link".
 *
 * Columns in table "link" available as properties of the model,
 * followed by relations of table "link" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $url
 *
 */
abstract class BaseLink extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'link';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Link|Links', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, url', 'required'),
			array('name, url', 'length', 'max'=>128),
			array('id, name, url', 'safe', 'on'=>'search'),
		);
	}

	/*public function relations() {
		return array(
			'userLinks' => array(self::HAS_MANY, 'UserLink', 'link_id'),
		);
	}*/

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'url' => Yii::t('app', 'Url'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}