<?php

/**
 * This is the model base class for the table "tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tag".
 *
 * Columns in table "tag" available as properties of the model,
 * followed by relations of table "tag" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $title
 * @property string $description
 *
 * @property TagAdmin[] $tagAdmins
 * @property TagEvent[] $tagEvents
 * @property TagIdea[] $tagIdeas
 * @property TagUser[] $tagUsers
 */
abstract class BaseTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tag|Tags', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name, title', 'length', 'max'=>128),
			array('description', 'safe'),
			array('title, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, title, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tagAdmins' => array(self::HAS_MANY, 'TagAdmin', 'tag_id'),
			'tagEvents' => array(self::HAS_MANY, 'TagEvent', 'tag_id'),
			'tagIdeas' => array(self::HAS_MANY, 'TagIdea', 'tag_id'),
			'tagUsers' => array(self::HAS_MANY, 'TagUser', 'tag_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'tagAdmins' => null,
			'tagEvents' => null,
			'tagIdeas' => null,
			'tagUsers' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}