<?php

/**
 * This is the model base class for the table "users_links".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersLinks".
 *
 * Columns in table "users_links" available as properties of the model,
 * followed by relations of table "users_links" available as properties of the model.
 *
 * @property string $ID
 * @property string $user_id
 * @property string $link_id
 *
 * @property Links $link
 * @property Users $user
 */
abstract class BaseUsersLinks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users_links';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersLinks|UsersLinks', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('user_id, link_id', 'required'),
			array('user_id', 'length', 'max'=>8),
			array('link_id', 'length', 'max'=>9),
			array('ID, user_id, link_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'link' => array(self::BELONGS_TO, 'Links', 'link_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'user_id' => null,
			'link_id' => null,
			'link' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('link_id', $this->link_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}