<?php

/**
 * This is the model base class for the table "ideas_members".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "IdeasMembers".
 *
 * Columns in table "ideas_members" available as properties of the model,
 * followed by relations of table "ideas_members" available as properties of the model.
 *
 * @property string $ID
 * @property string $idea_id
 * @property string $user_id
 * @property integer $type
 * @property integer $deleted
 *
 * @property Users $user
 * @property Ideas $idea
 */
abstract class BaseIdeasMembers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ideas_members';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'IdeasMembers|IdeasMembers', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('idea_id, user_id, type, deleted', 'required'),
			array('type, deleted', 'numerical', 'integerOnly'=>true),
			array('idea_id', 'length', 'max'=>9),
			array('user_id', 'length', 'max'=>8),
			array('ID, idea_id, user_id, type, deleted', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'idea' => array(self::BELONGS_TO, 'Ideas', 'idea_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'idea_id' => null,
			'user_id' => null,
			'type' => Yii::t('app', 'Type'),
			'deleted' => Yii::t('app', 'Deleted'),
			'user' => null,
			'idea' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('idea_id', $this->idea_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('type', $this->type);
		$criteria->compare('deleted', $this->deleted);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}