<?php

/**
 * This is the model base class for the table "qr_login".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QrLogin".
 *
 * Columns in table "qr_login" available as properties of the model,
 * followed by relations of table "qr_login" available as properties of the model.
 *
 * @property string $id
 * @property string $create_at
 * @property string $scan_at
 * @property string $user_id
 *
 * @property User $user
 */
abstract class BaseQrLogin extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'qr_login';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QrLogin|QrLogins', $n);
	}

	public static function representingColumn() {
		return 'create_at';
	}

	public function rules() {
		return array(
			//array('create_at', 'required'),
      array('create_at', 'default', 'value' => date('Y-m-d H:i:s'), 'setOnEmpty' => true, 'on' => 'insert'),        
			array('user_id', 'length', 'max'=>10),
			array('scan_at', 'safe'),
			array('scan_at, user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, create_at, scan_at, user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'create_at' => Yii::t('app', 'Create At'),
			'scan_at' => Yii::t('app', 'Scan At'),
			'user_id' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('create_at', $this->create_at, true);
		$criteria->compare('scan_at', $this->scan_at, true);
		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}