<?php

/**
 * This is the model base class for the table "users_skills".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersSkills".
 *
 * Columns in table "users_skills" available as properties of the model,
 * followed by relations of table "users_skills" available as properties of the model.
 *
 * @property string $ID
 * @property string $user_id
 * @property integer $skillset_id
 * @property integer $skill_id
 *
 * @property Skills $skill
 * @property Users $user
 * @property Skillsets $skillset
 */
abstract class BaseUsersSkills extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users_skills';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersSkills|UsersSkills', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('user_id, skillset_id, skill_id', 'required'),
			array('skillset_id, skill_id', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>8),
			array('ID, user_id, skillset_id, skill_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'skill' => array(self::BELONGS_TO, 'Skills', 'skill_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
			'skillset' => array(self::BELONGS_TO, 'Skillsets', 'skillset_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'user_id' => null,
			'skillset_id' => null,
			'skill_id' => null,
			'skill' => null,
			'user' => null,
			'skillset' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('skillset_id', $this->skillset_id);
		$criteria->compare('skill_id', $this->skill_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}