<?php

/**
 * This is the model base class for the table "ideas".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ideas".
 *
 * Columns in table "ideas" available as properties of the model,
 * followed by relations of table "ideas" available as properties of the model.
 *
 * @property string $ID
 * @property string $time_registered
 * @property string $time_updated
 * @property integer $status_id
 * @property string $website
 * @property string $video_link
 * @property integer $deleted
 *
 * @property IdeasStatuses $status
 * @property IdeasMembers[] $ideasMembers
 * @property IdeasTranslations[] $ideasTranslations
 */
abstract class BaseIdeas extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ideas';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ideas|Ideases', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('time_registered, time_updated, status_id, deleted', 'required'),
			array('status_id, deleted', 'numerical', 'integerOnly'=>true),
			array('time_registered, time_updated', 'length', 'max'=>11),
			array('website, video_link', 'length', 'max'=>128),
			array('website, video_link', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ID, time_registered, time_updated, status_id, website, video_link, deleted', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'status' => array(self::BELONGS_TO, 'IdeasStatuses', 'status_id'),
			'ideasMembers' => array(self::HAS_MANY, 'IdeasMembers', 'idea_id'),
			'ideasTranslations' => array(self::HAS_MANY, 'IdeasTranslations', 'idea_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'time_registered' => Yii::t('app', 'Time Registered'),
			'time_updated' => Yii::t('app', 'Time Updated'),
			'status_id' => null,
			'website' => Yii::t('app', 'Website'),
			'video_link' => Yii::t('app', 'Video Link'),
			'deleted' => Yii::t('app', 'Deleted'),
			'status' => null,
			'ideasMembers' => null,
			'ideasTranslations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('time_registered', $this->time_registered, true);
		$criteria->compare('time_updated', $this->time_updated, true);
		$criteria->compare('status_id', $this->status_id);
		$criteria->compare('website', $this->website, true);
		$criteria->compare('video_link', $this->video_link, true);
		$criteria->compare('deleted', $this->deleted);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}