<?php

/**
 * This is the model base class for the table "users_collabprefs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UsersCollabprefs".
 *
 * Columns in table "users_collabprefs" available as properties of the model,
 * followed by relations of table "users_collabprefs" available as properties of the model.
 *
 * @property string $ID
 * @property string $user_id
 * @property integer $collab_id
 *
 * @property Collabprefs $collab
 * @property Users $user
 */
abstract class BaseUsersCollabprefs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users_collabprefs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UsersCollabprefs|UsersCollabprefs', $n);
	}

	public static function representingColumn() {
		return 'ID';
	}

	public function rules() {
		return array(
			array('user_id, collab_id', 'required'),
			array('collab_id', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>8),
			array('ID, user_id, collab_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'collab' => array(self::BELONGS_TO, 'Collabprefs', 'collab_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ID' => Yii::t('app', 'ID'),
			'user_id' => null,
			'collab_id' => null,
			'collab' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ID', $this->ID, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('collab_id', $this->collab_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}