<?php

/**
 * This is the model base class for the table "db_query".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "DbQuery".
 *
 * Columns in table "db_query" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title
 * @property string $model
 * @property string $time_created
 *
 */
abstract class BaseDbQuery extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'db_query';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'DbQuery|DbQueries', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, model, time_created', 'required'),
			array('title', 'length', 'max'=>255),
			array('id, title, model, time_created', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'model' => Yii::t('app', 'Model'),
			'time_created' => Yii::t('app', 'Time Created'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('model', $this->model, true);
		$criteria->compare('time_created', $this->time_created, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}