<?php

/**
 * This is the model base class for the table "idea_link".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ideaLink".
 *
 * Columns in table "idea_link" available as properties of the model,
 * followed by relations of table "idea_link" available as properties of the model.
 *
 * @property string $id
 * @property string $idea_id
 * @property string $link_id
 *
 * @property Link $link
 * @property idea $idea
 */
abstract class BaseideaLink extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'idea_link';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Link|Links', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('idea_id, title, url', 'required'),
			array('url', 'url', 'defaultScheme' => 'http'),
			array('idea_id', 'length', 'max'=>8),
			array('id, idea_id, link_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idea' => array(self::BELONGS_TO, 'idea', 'idea_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'idea_id' => null,
			'idea' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('idea_id', $this->idea_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}