<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => 'Odustani',
  'Drop files here to upload' => 'Ovdje stavite datoteku da se prenese.',
  'Failed' => 'Neuspjelo',
  'Loading...' => 'Učitava...',
  'No more results!' => 'Nema više rezultata!',
  'Oops, nothing found!' => 'Oops, ništa nije nađeno!',
  'Page' => 'Stranica',
  'Scan QR code with phone to login' => '',
  'The files are being uploaded, if you leave now the upload will be cancelled.' => 'Datoteke se prenašaju. Ako sada napustite stranicu, prijenos će biti prekinut.',
  'Upload a file' => 'Prenesi datoteku',
  '{file} has invalid extension. Only {extensions} are allowed.' => '{file} ima krivi nastavak. Samo {extensions} su dozvoljeni.',
  '{file} is empty, please select files again without it.' => '{file} je prazan. Ponovno označite dokumente bez ovog praznog.',
  '{file} is too large, maximum file size is {sizeLimit}.' => '{file} je prevelik. Najveći mogući format je {sizeLimit}.',
  '{file} is too small, minimum file size is {minSizeLimit}.' => '{file} je premalen. Najmanji mogući format je {sizeLimit}.',
);
