<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<?php echo $modelClass; ?>|<?php echo $this->pluralize($modelClass); ?>' => '',
  'Activkey' => '',
  'Address' => 'Naslov',
  'Advanced Search' => 'Napredno iskanje',
  'All' => 'Vsi',
  'Available' => 'Razpoložljivi',
  'Avatar Link' => 'Uporabniška slika',
  'City|Cities' => 'Mesto|Mesta',
  'ClickIdea|ClickIdeas' => '',
  'ClickUser|ClickUsers' => '',
  'Collabpref|Collabprefs' => '',
  'Country|Countries' => 'Država|Države',
  'Create' => 'Ustvari',
  'Create At' => 'Ustvari ob',
  'Delete' => 'Izbriši',
  'Deleted' => 'Izbrisano',
  'Description' => '',
  'Description Public' => '',
  'Email' => 'Email',
  'Fields with' => '',
  'ID' => '',
  'IdeaMember|IdeaMembers' => '',
  'IdeaStatus|IdeaStatuses' => '',
  'IdeaTranslation|IdeaTranslations' => '',
  'Idea|Ideas' => '',
  'Index' => '',
  'Language' => '',
  'Language Code' => '',
  'Language|Languages' => '',
  'Lastvisit At' => '',
  'Link|Links' => '',
  'List' => '',
  'Manage' => '',
  'Name' => '',
  'Newsletter' => '',
  'No' => 'Ne',
  'Password' => '',
  'Pitch' => '',
  'Row' => '',
  'Save' => 'Shrani',
  'Search' => '',
  'SkillsetSkill|SkillsetSkills' => '',
  'Skillset|Skillsets' => '',
  'Skill|Skills' => '',
  'Status' => 'Status',
  'Superuser' => '',
  'Surname' => 'Priimek',
  'Table' => 'Tabela',
  'Time' => 'Čas',
  'Time Registered' => '',
  'Time Updated' => '',
  'Title' => 'Naslov',
  'Translation' => '',
  'Translation|Translations' => '',
  'Tweetpitch' => '',
  'Type' => 'Tip',
  'Update' => 'Posodobi',
  'Url' => 'Url',
  'UserCollabpref|UserCollabprefs' => '',
  'UserLink|UserLinks' => '',
  'UserShare|UserShares' => '',
  'UserSkill|UserSkills' => '',
  'User|Users' => '',
  'Video Link' => '',
  'View' => 'Pregled',
  'Website' => '',
  'Yes' => '',
  'Your request is invalid.' => '',
  'are required' => '',
  'password' => 'geslo',
  '{$label}' => '',
);
