<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => 'Prekliči',
  'Drop files here to upload' => 'Za prenos spustite datoteko tukaj',
  'Failed' => 'Ni uspelo',
  'Loading QR code login...' => 'Nalagam QR kodo',
  'Loading...' => 'Nalagam ...',
  'No more results!' => 'Ni več zadetkov!',
  'Oops, nothing found!' => 'Ups, nič ni bilo najdeno!',
  'Page' => 'Stran',
  'QR code login is safer and faster way to login. First time we will pair your phone with your profile. You will then be able to login without the need of writing your email and password. <br />Advisable in cyber cafes where you don\'t know if they are tracking your key strokes.' => 'Prijava s QR kodo je hitrejša in varnejša. Pri prvi prijavi bomo povezali vaš telefon in profil, nato pa se boste lahko prijavljali brez uporabe uporabniškega imena in gesla. <br />Tak način prijave priporočamo predvsem v internet kafejih, saj ne morete vedeti ali tisti računalniki beležijo tipke in posledično vaše geslo.',
  'Scan QR code with phone to login' => 'Za prijavo poskeniraj QR kodo s telefonom',
  'Source' => 'Izvor',
  'The files are being uploaded, if you leave now the upload will be cancelled.' => 'Če boste zapustili stran bo prenos datotek preklican.',
  'Upload a file' => 'Posnemi datoteko',
  '{file} has invalid extension. Only {extensions} are allowed.' => 'Datoteka {file} ima napano končnico. Le sledeče končnice so dovoljene  {extensions}.',
  '{file} is empty, please select files again without it.' => 'Datoteka {file} je prazna, prosimo izberite drugo datoteko.',
  '{file} is too large, maximum file size is {sizeLimit}.' => 'Datoteka {file} je prevelika, maksimalna velikost je {sizeLimit}.',
  '{file} is too small, minimum file size is {minSizeLimit}.' => 'Datoteka {file} je premajhna, minimalna velikost je {minSizeLimit}.',
);
