<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '
		Ideja se je porodila konec oktobra 2012 na dogodku v PopUp domu. Ob pogovoru z enim izmed ustanovitljev ljubljanskega coworkinga sem prišel na idejo, ki bi razširila ta koncept preko fizičnih meja, saj sem imel tudi sam v preteklosti problem iskanja zanesljivih partnerjev za uresničevanje svojih zamisli. Problem sem videl v relativni majhnosti posameznikovega socialnega kroga, ki zajema predvsem ljudi znotraj njegove glavne panoge.
		Sredi decembra sva se povezala z Blažem, ki je ravno takrat reševal tak problem. Skupaj sva pričela razvijati koncept ideje, ko se nama je pridružil tudi tretji član z istim problemom, ki trenutno ni več aktiven. 
		Do konca februarja smo koncept pripeljali tako daleč, da smo ga na Sedi 5 v Kinu Šiška tudi predstavili. Pozitiven odziv poslušalcev nas je motiviral, da smo se odločili, da projekt tudi realiziramo. Po predstavitvi se nam je pridružil tudi Jure in v začetku marca smo se lotili realizacije.' => '',
  ' Please check your email. <br />Instructions were sent to your email address.' => 'Prosimo preverite vaš email. <br />Navodila so bila poslana na navedeni email.',
  'Add some extra information like what you can offer...' => 'Navedite nekaj dodatnih informacij, kot na primer, kaj lahko ponudite...',
  'Add some links.' => 'Dodajte povezave.',
  'Add some skills.' => 'Dodajte znanja.',
  'Adding more skills will improve your profile visibility.' => 'Dodajanje znanj bo izboljšalo vidnost vašega profila.',
  'Are you sure you want to delete this item?' => 'Ste prepričani, da želite to izbrisati?',
  'At the end we will append link to your project like this <strong>{url}</strong>' => 'Na konec vam bomo pripeli takšno povezavo na vaš projekt <strong>{url}</strong>',
  'At the end we will append this link to your project <a href="{url}" target="_blank">{url}</a>' => 'Na konec vam bomo pripeli še to povezavo na vaš projekt <a href="{url}" target="_blank">{url}</a>',
  'Avatar saved.' => 'Progilna slika shranjena.',
  'Choose the language you want to write your idea in. Later you can add more translations for the same idea' => 'Izberite v katerem jeziku želite opisati vašo idejo. Kasneje lahko dodate prevode v ostale jezike.',
  'Chose a name to represent your link.' => 'Izberite ime, ki bo predstavljalo vašo povezavo.',
  'Could not delete open position.' => 'Ni bilo možno odstraniti odprte pozicije.',
  'Could not remove project from your account.' => 'Ni bilo možno odstraniti projekta.',
  'Could not save project translation.' => 'Ni bilo možno shraniti prevoda projekta.',
  'Could not save uploaded file. The upload was cancelled, or server error encountered' => 'Ni nam uspelo shraniti naložene datoteke. Nalaganje je bilo preklicano, predvidoma zaradi napake na strežniku',
  'Create or take part in a project.' => 'Ustvari ali postani član projekta.',
  'Describe your project in detail.' => 'Opišite vaš projekt bolj podrobno.',
  0 => '',
  'Describe your project with 120 characters or less for sharing on social networks.' => 'Za deljenje na socialnih omrežjih opiši svoj projekt z 120 znaki ali manj.',
  'Describe your project with comma separated keywords to increase visibility of your project.' => 'Opišite vaš projekt z uporabo ključnih besed. Le-te ločite z vejicami. S tem boste povečali vidnost vašega projekta na strani.',
  'Description isn\'t published!' => 'Opis ni javno objavljen!',
  'Drop file here to change your profile picture.' => 'Tu odložite datoteko, če želite spremeniti vašo profilno sliko.',
  'Email can\'t be changed at this time.' => 'Email naslova trenutno ni mogoče spremeniti.',
  'Email is incorrect.' => 'Nepravilen email naslov.',
  'Fields with <span class="required">*</span> are required.' => 'Polja z <span class="required">*</span> morajo biti obvezno izpolnjena.',
  'File has an invalid extension, it should be one of {file}.' => 'Datoteka ima neveljavno končnico. Samo slednje so dovoljene {file}.',
  'File is empty!' => 'Datoteka je prazna!',
  'File is too large!' => 'Datoteka je prevelika!',
  'Fill up your profile details.' => 'Izpolnite podrobnosti vašega profila.',
  'Getting content length is not supported.' => 'Pridobivanje dolžine vsebine ni podprto.',
  'I have read and agree to the following Terms of Use {tos}' => 'Prebral sem in se strinjam s Pogoji uporabe {tos}',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Če imate poslovno ali kakršnokoli drugo vprašanje, vas prosimo da izpolnete kontaktni obrazec. Hvala.',
  'If you wish to be invited or notified when we go live please leave your email address below.' => 'Če želite biti obveščeni o novostih in o tem kdaj se bo storitev odprla za širšo javnost nam prosim spodaj pustite vaš email.',
  'In private beta member invitations are disabled.' => 'Povabila članov so izklopljena v privatni beti.',
  'Incorrect activation URL.' => 'Nepravilen aktivacijski URL.',
  'Incorrect password (minimal length 4 symbols).' => 'Nepravilno geslo (najmanjša dolžina so 4 znaki)',
  'Incorrect symbols (A-z0-9).' => 'Nepravilni znaki (A-z0-9).',
  'Incorrect username (length between 3 and 20 characters).' => 'Nepravilno uporabniško ime (dolžina je omejena na 3 do 20 znakov)',
  'Incorrect username or password.' => 'Nepravilno uporabniško ime ali geslo.',
  'Invalid request. Please do not repeat this request again.' => 'Neveljavna zahteva. Prosimo ne ponovite te zahteve.',
  'Invitation removed!' => 'Povabilo odstranjeno!',
  'Invitation send.' => 'Povabilo poslano.',
  'Invitation to add new member send.' => 'Povabilo je bilo poslano novemu članu.',
  'Letters are not case-sensitive.' => 'Črke niso občutljive na velikost',
  'Link successfully saved to profile.' => 'Povezava uspešno shranjena na profil.',
  'Link to video presentation of project.' => 'Povezava do video predstavitve projekta.',
  'Member removed from project' => 'Član je bil odstranjen iz projekta.',
  'Message can\'t be empty!' => 'Sporočilo ne sme biti prazno!',
  'Minimal password length 4 symbols.' => 'Minimalna dolžina gesla 4 znake.',
  'My designation at cofinder is to take care of our online foundations.' => '',
  'Name of skill you posess.' => 'Ime vaše spretnosti oz znanja',
  'Name of skill your candidate should posess.' => 'Ime spretnosti oz znanja, ki ga more imeti kandidat.',
  'New password is saved.' => 'Novo geslo je shranjeno.',
  'Newsletter sent succesfully.' => 'Newsletter uspešno poslan.',
  'No files were uploaded.' => 'Nobena datoteka ni bila naložena.',
  'No results found with this filters.' => 'Nobenega rezultata ne najdem z uporabo teh filtrov.',
  'No search query.' => 'Ni iskalnega niza po katerem bi iskal.',
  'Not able to invite this person to this project.' => 'Ni bilo mogoče povabiti te osebe k projektu.',
  'Old Password is incorrect.' => 'Staro geslo je nepravilno.',
  'Oops! Something went wrong. Unable to add new member to project.' => 'Ups! Nekaj je bilo narobe. Ni nam uspelo dodati novega člana k projektu.',
  'Oops! Something went wrong. Unable to remove member from project.' => 'Ups! Nekaj je bilo narobe. Ni nam uspelo odstraniti člana od projekta.',
  'Oops! This project does not exist.' => 'Oops! Ta projekt ne obstaja.',
  'Open position deleted.' => 'Odprta pozicija izbrisana.',
  'Password is incorrect.' => 'Nepravilno geslo.',
  'Personal information saved.' => 'Osebne informacije shranjene.',
  'Please enable JavaScript to use file uploader.' => 'Za nalaganje datotek, prosimo omogočite JavaScript.',
  'Please enter the letters as they are shown in the image above.' => 'Prosimo vtipkajte črke, kot so prikazane v gornji sliki.',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Prosimo vtipkajte črke, kot so prikazane v gornji sliki.<br/>Črke niso odvisne od velikosti.',
  'Please fill out the following form with your login credentials' => 'Prosimo, da izpolnite obrazec z vašimi vpisnimi podatki',
  'Please select correct skill group.' => 'Prosimo izberite pravo skupino znanj.',
  'Position successfully opened.' => 'Pozicija uspešno ustvarjena.',
  'Problem saving link. Please check fields for correct values.' => 'Povezava za reševanje problemov. Prosimo preverite če imajo polja prave vrednosti.',
  'Problem saving skill. Please check fields for correct values.' => 'Ni bilo možno shraniti znanja. Prosimo preverite vsa polja za pravilne vrednosti.',
  'Profile details saved.' => 'Profil uspešno shranjen.',
  'Profile details saved. Please check your mail for activation code.' => '',
  'Project has a presentational web page' => 'Projekt ima predstavitveno spletno stran',
  'Project has a video' => 'Projekt ima video',
  'Project removed from your account successfully.' => 'Projekt uspešno odstranjen iz vašega profila.',
  'Project removed successfully!' => 'Projekt uspešno odstranjen!',
  'Project successfully removed.' => 'Projekt uspešno odstranjen.',
  'Project successfully saved.' => 'Projekt uspešno shranjen.',
  'Project successfully updated.' => 'Projekt uspešno posodobljen.',
  'Retype password is incorrect.' => 'Ponovitev gesla napačna.',
  'Select group which represents your skill the closest.' => 'Izberi skupino, ki se ujema s tvojimi znanji',
  'Select how much time you have to work on projects.' => 'Izberi koliko časa lahko posvetiš delu na projektu',
  'Selecting an avatar will make you more recognizable.' => 'Na podlagi profilne slike se boste z ostalimi uporabniki lažje prepoznali, ko se srečate v živo',
  'Server error. Upload directory isn\'t writable.' => 'Napaka na strežniku. V mapo za nalaganje se ne da pisati',
  'Settings saved.' => 'Nastavitve shranjene.',
  'Status of project.' => 'Status projekta',
  'Subscribe to newsletter and get all important updates.' => 'Prijavite se na novičnik in bodite na tekočem z vsemi pomembnimi novostmi',
  'Success!' => 'Uspelo!',
  'Successfully saved project translation!' => 'Uspešno shranjen prevod projekta.',
  'Successfully updated collaboration preferences!' => 'Uspešno osvežene preference načina sodelovanja',
  'Taking care of overall design is my primary focus here on cofinder.' => '',
  'Thank you for your interest!' => 'Hvala za izkazano zanimanje',
  'Thank you for your registration. Contact Admin to activate your account.' => 'Hvala za vašo registracijo. Kontaktirajte administratorja za aktivacijo vašega računa.',
  'Thank you for your registration. Please check your email for confirmation code.' => 'Hvala za vašo registracijo. Prosim preverite če ste na navedeni email prejeli potrditveno kodo.',
  'Thank you for your registration. Please check your email or login.' => 'Hvala za vašo registracijo. Prosimo preverite vaš email ali se prijavite.',
  'Thank you for your registration. Please check your email.' => 'Hvala za vašo registracijo. Prosimo preverite email, ki ste ga navedli ob registraciji.',
  'Thank you for your registration. Please {login}.' => 'Hvala za vašo registracijo. Prosimo prijavite se {login}.',
  'Thank you for your registration. You will shortly receive our confirmation email.' => 'Hvala za vašo registracijo. V kratkem boste prejeli potrditveni email.',
  'The files are being uploaded, if you leave now the upload will be cancelled.' => 'Datoteke se nalagajo, če zapustite stran sedaj bo nalaganje preklicano',
  'The only constant in life is change so it\'s important not to fall asleep on past successes or to give up at the sight of problems.' => '',
  'The requested page does not exist.' => 'Želena stran ne obstaja',
  'There was a problem activating your account!' => '',
  'This action will change your password!
Are you sure?' => 'Ta akcija vam bo spremenila geslo!
Ali ste prepričani?',
  'This action will create an invitation.
Are you sure?' => 'Ta akcija bo poslala vabilo.
Ali ste prepričani?',
  'This action will deactivate your account.
Are you sure?' => 'Ta akcija vam bo zaklenila dostop!
Ali ste prepričani?',
  'This form will generate an invite for specific email address and return invite address <strong>Invitation email will not be sent!</strong>.' => 'Ta forma bo ustvarila povezavo do povabila za izbran email.<strong>Povabilo ne bo poslano na email.</strong>',
  'This is your pitch. Be short and to the point.' => 'To je vaš pitch. Bodite kratki in jedernati.',
  'This user is already invited.' => 'Ta uporabnik je že povabljen.',
  'This user\'s email address already exists.' => 'Ta email je že zaseden s strani enega od uporabnikov.',
  'This user\'s name already exists.' => 'To uporabniško ime je že v uporabi.',
  'To activate you account please go to {activation_url}' => 'Za aktivacijo vašega profila prosim pojdite na {activation_url}',
  'To deactivate your account change "Account status" to off and click deactivate. You will then be loged out of the system.' => 'Za deaktivacijo računa spremenite "Status računa" na izključeno in kliknite deaktiviraj račun. Nato boste odjavljeni iz sistema.',
  'Translation successfully removed!' => 'Prevod uspešno odstranjen!',
  'Translations saved.' => 'Prevodi shranjeni.',
  'Try filling up your personal information.' => 'Potrudite se izpolniti vaše osebne informacije.',
  'Try to fill as many fields as posible to describe your perfect candidate. If you are not sure or you don\'t require certain aspects just leave them blank.' => 'Poizkusite izpolniti čimveč relevantnih polj, ki definirajo vašega idealnega kandidata. Če ne veste kaj potrebujete oziroma česa ne zahtevate, pustite tista polja prazna.',
  'Unable to add skill.' => 'Ni mogoče dodati znanj.',
  'Unable to create project.' => 'Ni bilo mogoče ustvariti projekta',
  'Unable to remove link.' => 'Ni mogoče odstraniti povezave.',
  'Unable to remove project from your account.' => 'Ni mogoče odstraniti projekta iz vašega računa.',
  'Unable to remove skill.' => 'Ni mogoče odstraniti znanja.',
  'Unable to remove translation from project.' => 'Ni mogoče odstraniti prevoda projekta.',
  'Unable to save open position.' => 'Ni bilo možno shraniti odprte pozicije.',
  'Unable to save profile details.' => 'Ni bilo možno shraniti profila.',
  'Unable to send invitation! Eather user is already invited or the email you provided is incorrect.' => 'Ni bilo mogoče poslati povabila! Verjetno je uporabnik že povabljen ali pa ste vpisali napačno elektronsko pošto.',
  'Unable to update collaboration preferences.' => 'Ni mogoče posodobiti preferenčnega načina sodelovanja.',
  'Unable to update project.' => 'Ni bilo možno',
  'Username is incorrect.' => 'Uporabniško ime ni pravilno.',
  'We are a group of enthusiasts on a mission to help anyone with a great idea to assemble a successful startup team capable of creating a viable business. We are developing a web platform through which you will be able to share your ideas with the like minded entrepreneurs and search for interesting projects to join.' => 'Smo ekipa katero združuje skupna želja po rešitvi problema na katerega smo naleteli na svojih poteh realizacije idej v realne produkte in storitve. Ustvarjamo spletno mesto, ki bo pomagalo vsem z dobrimi idejami najti člane ekipe, kateri bodo pomagali dobro idejo spremeniti v realnost. Oziroma omogočilo vsem, ki si želijo sodelovati pri ustvarjanju novih izdelkov in storitev, da najdejo idejo v katero verjamejo in se pridružijo ekipi ki jo uresničuje.',
  'We are curently in a private beta stage and as such only except registrations with invitations.' => 'Trenutno smo v fazi omejenega beta testiranja. Registracija je možna le preko vabila.',
  'We purge all deactivated accounts on first day of each month. You have until then to reactivate it by clicking "Lost Password?" in login form.' => 'Vsi deaktivirani računi so permanentno izbrisani vsak prvi dan novega meseca. Do takrat imate čas, da svoj račun ponovno aktivirate in sicer tako, da kliknete na "Izgubljeno geslo?" v obrazcu za prijavo.',
  'What are you calling it? One or two words please, you can always change it later.' => 'Kako se imenuje? Z eno ali dvemi besedami prosim. Kasneje lahko kadarkoli spremenite.',
  'What is your prefered Collaboration.' => 'Kakšen način sodelovanja vam ustreza.',
  'What kind of Collaboration do you prefer when working on a project.' => 'Kakšen način sodelovanja si želite za delo na projektih.',
  'When we purge your account all data connected to it will be removed as well.' => 'Ko izbrišemo vaš račun, bodo z njim izgubljeni vsi podatki ki jih vsebuje.',
  'While you wait for our confirmation email fill in some of your profile information.' => 'Medtem ko čakate na potrditveni email, vas prosimo da izpolnete nekaj osnovnih informacij na vašem novem profilu.',
  'With the <span>right team</span> any <span>idea</span> can <br />change your life' => 'S <span>pravo ekipo</span> vam lahko katerakoli <span>ideja</span> spremeni življenje',
  'Within cofinder I take care of development while motivating the team and try to engage others to join our project.' => '',
  'Wrong candidate ID supplied, could not update candidate.' => 'Napačna koda kandidata posredovana zato ga ni bilo možno posodobiti.',
  'You account is activated.' => 'Vaš račun je aktiviran.',
  'You account is already active.' => 'Vaš račun je že aktiviran.',
  'You account is blocked.' => 'Vaš račun je blokiran.',
  'You account is not activated.' => 'Vaš račun ni aktiviran.',
  'You already have this link.' => 'To povezavo že imate.',
  'You already have this skill.' => 'To znanje že imate dodano.',
  'You are about to delete this project!
Are you sure?' => 'S tem klikom boste izbrisali projekt!
Ali ste prepričani?',
  'You are about to delete this translation!
Are you sure?' => 'Odstranili boste ta prevod!
Ali ste prepričani?',
  'You are about to join this project!
Are you sure?' => 'Pridružili se boste temu projektu!
Ali ste prepričani?',
  'You are about to leave this project!
You will have to be re invited to be a member.
Are you sure?' => 'Če boste zapustili projekt vas bodo morali k njamu povabiti ponovno!
Ali ste prepričani?',
  'You are about to remove this candidate!
Are you sure?' => 'Odstranili boste tega kandidata!
Ali ste prepričani?',
  'You are about to remove this member from the team!
Are you sure?' => 'Odstranili boste člana ekipe!
Ali ste prepričani?',
  'You are invited to join cofinder' => 'Vabimo vas, da se pridružite cofinder-ju',
  'You may optionally enter a comparison operator (&lt;, &lt;=, &gt;, &gt;=, &lt;&gt; or =) at the beginning of each of your search values to specify how the comparison should be done.' => '',
  'You must agree to the terms and conditions' => 'Soglašati morate s pogoji uporabe',
  'You must be loged in to contact this person.' => 'Če želite kontaktirati to osebo, se morate najprej prijaviti.',
  'You registered from {site_name}' => 'Registrirali ste se preko {site_name}',
  'Your message was sent.' => 'Vaše sporočilo je bilo poslano.',
  'Your request is invalid.' => 'Vaša zahteva je neveljavna.',
  '{file} has invalid extension. Only {extensions} are allowed.' => '{file} ima neveljavno končnico. Samo {extensions} so dovoljene.',
  '{file} is empty, please select files again without it.' => '{file} je prazna, prosimo izberite ponovno datoteke brez te ki je prazna.',
  '{file} is too large, maximum file size is {sizeLimit}.' => '{file} je prevelika, največja velikost datoteke je lahko {sizeLimit}.',
  '{username} welcome to cofinder!' => '{username} dobrodošel v cofinder-ju!',
);
