<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add some links.' => '',
  'Add some skils.' => '',
  'Could not save uploaded file. The upload was cancelled, or server error encountered' => '',
  'Create or become a part of a project.' => '',
  'Drop file here to change your profile picture.' => '',
  'Email can\'t be changed at this time.' => '',
  'Email is incorrect.' => '',
  'Fields with <span class="required">*</span> are required.' => '',
  'File has an invalid extension, it should be one of {file}.' => '',
  'File is empty!' => '',
  'File is too large!' => '',
  'Fill up your profile details.' => '',
  'Getting content length is not supported.' => '',
  'Incorrect activation URL.' => '',
  'Incorrect password (minimal length 4 symbols).' => '',
  'Incorrect recovery link.' => '',
  'Incorrect symbols (A-z0-9).' => '',
  'Incorrect username (length between 3 and 20 characters).' => '',
  'Incorrect username or password.' => '',
  'Letters are not case-sensitive.' => '',
  'Minimal password length 4 symbols.' => '',
  'New password is saved.' => '',
  'Newsletter sent successfully.' => '',
  'No files were uploaded.' => '',
  'Old Password is incorrect.' => '',
  'Oops! This project does not exist.',
  'Oops! Something went wrong. Unable to remove project from your account.' => '',
  'Oops! Something went wrong. Unable to update collaboration preferences.' => '',
  'Oops! Something went wrong. Unable to update skills.' => '',
  'Oops! Something went wrong. Unable to remove translation from project.' => '',
  'Oops! Something went wrong. Unable to delete project.' => '',
  'Oops! Something went wrong. Unable to add new member to project.' => '',
  'Oops! Something went wrong. Unable to remove member from project.' => '',
  'Oops! Something went wrong. Unable to add new candidate to project.' => '',
  'Oops! Something went wrong. Unable to remove candidate from project.' => '',
  'Password is incorrect.' => '',
  'Please activate you account go to {activation_url}' => '',
  'Please check your email. An instructions was sent to your email address.' => '',
  'Please enable JavaScript to use file uploader.' => '',
  'Please enter the letters as they are shown in the image above.' => '',
  'Please enter your email address.' => '',
  'Please fill out the following form with your login credentials:' => '',
  'Problem saving link. Please check fields for correct values.' => '',
  'Project has a presentational web page' => '',
  'Project has a video' => '',
  'Retype Password is incorrect.' => '',
  'Selecting an avatar will give you more visibility.' => '',
  'Server error. Upload directory isn\'t writable.' => '',
  'Subscribe to newsletter and get all important updates.' => '',
  'Success!' => '',
  'Thank you for your registration. Contact Admin to activate your account.' => '',
  'Thank you for your registration. Please check your email or login.' => '',
  'Thank you for your registration. Please check your email.' => '',
  'Thank you for your registration. Please {{login}}.' => '',
  'The files are being uploaded, if you leave now the upload will be cancelled.' => '',
  'This action will change your password!
Are you sure?' => '',
  'This action will deactivate your account.
Are you sure?' => '',
  'This user\'s email address already exists.' => '',
  'This user\'s name already exists.' => '',
  'To deactivate your account change its status to off and click deactivate. You will then be loged out of the system.' => '',
  'Try filling up your personal information.' => '',
  'Unable to remove link.' => '',
  'We are a group of enthusiasts on a mission to help anyone with a great idea to assemble a successful startup team capable of creating a viable business. We are developing a web platform through which you will be able to share your ideas with the same-minded entrepreneurs and search for interesting projects to join.' => '',
  'We purge all deactivated accounts on first of each month. You have until then to reactivate it by clicking "Lost Password?" in login form.' => '',
  'What is your prefered colaboration.' => '',
  'When we purge your account all data connected to it will be removed as well.' => '',
  'You account is activated.' => '',
  'You account is active.' => '',
  'You account is blocked.' => '',
  'You account is not activated.' => '',
  'You already have this link.' => '',
  'You are about to delete this project!
Are you sure?' => '',
  'You are about to leave this project!
Are you sure?' => '',
  'You have requested the password recovery site {site_name}' => '',
  'You have requested the password recovery site {site_name}. To receive a new password, go to {activation_url}.' => '',
  'You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b> or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.' => '',
  'You registered from {site_name}' => '',
  'Your request is invalid.' => '',
  '{file} has invalid extension. Only {extensions} are allowed.' => '',
  '{file} is empty, please select files again without it.' => '',
  '{file} is too large, maximum file size is {sizeLimit}.' => '',
);
