<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'After I opened a new position for my project I immediately got contacted by interesting people.' => '',
  'Any claim relating to Cofinder\'s web site shall be governed by the laws of the State of Slovenia without regard to its conflict of law provisions.' => '',
  'Any of the information we collect from you may be used in one of the following ways: ' => '',
  'As a young startup we were looking for specific type of profesionals. We were able to find them quickly with the help of Cofinder.' => '',
  'Boštjan from Studio 404' => '',
  'By accessing this website, you agree to be bound by its Terms and Conditions of Use, all applicable laws and regulations and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this website. The materials contained in it are protected by applicable copyright and trade mark law.' => '',
  'By using our site, you consent to our online privacy policy.' => '',
  'Cofinder has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Cofinder of the site. Use of any such linked web site is at the user\'s own risk.' => '',
  'Cofinder may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.' => '',
  'Cofinder uses its own cookies at the website www.cofinder.eu  and at the same time enables certain third-parties to install their cookies on the device of the user (i.e. third-party cookies).' => '',
  'Cookies, and the information gathered with their help, do not offer the details that would allow the provider to identify the user in a way that would violate legislation on the protection of personal data, and do not enable the provider to discover the true identity of visitors. Users can set permissions for blocking or allowing cookies at any time in the web browser they use to access www.cofinder.eu <br />' => '',
  'If we decide to change our privacy policy, we will post those changes on this page, and/or send an email notifying you of any changes. ' => '',
  'In no event shall Cofinder or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Cofinder\'s Internet site, even if Cofinder or a Cofinder authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.' => '',
  'Information regarding individual cookies, parties managing the data acquired through the use of cookies, the intended purpose of the collected data, and the duration of each cookie are listed in the following chart:' => '',
  'Permission is granted to temporarily download one copy of the materials (information or software) on Cofinder\'s web site for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:' => '',
  'Peter from Biometrics' => '',
  'The idea was born during the conversation that took place in October, 2012 at PopUp home. Talking to one of the founders of Slovenia co-working made me realise that the concept of co-working could be introduced to a broader community by the online platform. It would help solve a problem of finding the right team to build new products and services. Blaž joined me in the middle of December. He has been facing the same problem, a difficulty finding a reliable team outside his social circles. Soon after that, the third member joined our team. At the end of February, 2013 we developed and presented our concept to Slovenia\\\'s co-working community. A positive feedback gave us more than enough motivation to proceed with the development of the web platform. The forth member joined our team and the development process soon after that presentation' => '',
  'The materials appearing on Cofinder\'s web site could include technical, typographical, or photographic errors. Cofinder does not warrant that any of the materials on its web site are accurate, complete, or current. Cofinder may make changes to the materials contained on its web site at any time without notice. Cofinder does not, however, make any commitment to update the materials.' => '',
  'The materials on Cofinder\'s web site are provided "as is". Cofinder makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Cofinder does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.' => '',
  'The provider may use cookies to ensure that the user receives a smooth and user-friendly experience while browsing and viewing the website. Cookies can also be used to study users, track visitor traffic (for statistical purposes) and improve the efficiency of advertising.<br />	' => '',
  'The provider, Cofinder, uses browser cookies (from here on: cookies) at the following website www.cofinder.eu Cookies are text files that are stored on the device of a user visiting a website. When the user returns to the website, the provider can access the information that was saved on the device of the user through the use of cookies.' => '',
  'This license shall automatically terminate if you violate any of these restrictions and may be terminated by Cofinder at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.' => '',
  'This online privacy policy applies only to information collected through our website and not to information collected offline.' => '',
  'To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)' => '',
  'To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)' => '',
  'To personalize your experience (your information helps us to better respond to your individual needs)' => '',
  'To send periodic emails The email address you provide may be used to send you information, respond to inquiries, and/or other requests or questions.' => '',
  'We are a group of enthusiasts with a mission to help anyone with a great idea to assemble a successful start-up team capable of creating a viable business. We are developing a web platform through which you will be able to share your ideas with the like-minded entrepreneurs and search for interesting projects.' => '',
  'We collect information from you when you register on our site, subscribe to our newsletter or respond to a survey. 
      <br /><br />
      When ordering or registering on our site, as appropriate, you may be asked to enter your: name or e-mail address. You may, however, visit our site anonymously.
      <br /><br />
      Google, as a third party vendor, uses cookies to serve ads on your site. Google\'s use of the DART cookie enables it to serve ads to your users based on their visit to your sites and other sites on the Internet. Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.' => '',
  'We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.' => '',
  'We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.' => '',
  'Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information
      <br /><br />
      We use cookies to understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.' => '',
  'attempt to decompile or reverse engineer any software contained on Cofinder\'s web site;' => '',
  'modify or copy the materials;' => '',
  'remove any copyright or other proprietary notations from the materials; or' => '',
  'transfer the materials to another person or "mirror" the materials on any other server.' => '',
  'use the materials for any commercial purpose, or for any public display (commercial or non-commercial);' => '',
);
