<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Cancel' => '',
  'Drop files here to upload' => '',
  'Failed' => '',
  'Loading QR code login...' => '',
  'Loading...' => '',
  'No more results!' => '',
  'Oops, nothing found!' => '',
  'Page' => '',
  'QR code login is safer and faster way to login. First time we will pair your phone with your profile. You will then be able to login without the need of writing your email and password. <br />Advisable in cyber cafes where you don\'t know if they are tracking your key strokes.' => '',
  'Scan QR code with phone to login' => '',
  'Source' => '',
  'The files are being uploaded, if you leave now the upload will be cancelled.' => '',
  'Upload a file' => '',
  '{file} has invalid extension. Only {extensions} are allowed.' => '',
  '{file} is empty, please select files again without it.' => '',
  '{file} is too large, maximum file size is {sizeLimit}.' => '',
  '{file} is too small, minimum file size is {minSizeLimit}.' => '',
);
